[HYPI-1064] Limit docker retry

diff --git a/.github/workflows/deploy-mekadbms-bin.yml b/.github/workflows/deploy-mekadbms-bin.yml
--- a/.github/workflows/deploy-mekadbms-bin.yml
+++ b/.github/workflows/deploy-mekadbms-bin.yml
@@ -86,12 +86,22 @@ jobs:
       - name: Install Docker (Mac)
         if: contains(matrix.platform.os_name, 'macOS')
         run: |
-          brew install --cask docker
+          brew install --cask --no-quarantine docker
           brew install bash-completion
           brew install docker-completion
+          set -e
+          set -o xtrace
           # initial open can fail so retry
+          cnt="1"
           while (! docker ps &>/dev/null ); do
-            open -a Docker; sleep 1
+            open -a Docker; sleep 10
+            cnt=$((cnt+1))
+            if [[ $cnt -gt 6 ]] ; then
+              echo "Docker failed to start"
+              exit -1
+            else
+              echo "Docker not running...waiting and retrying"
+            fi            
           done
           ls -l /usr/local/bin/docker*
           docker ps
